# Generated by Django 3.2.9 on 2021-11-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='coat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='good_with_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='house_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
