# Generated by Django 3.2.9 on 2021-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20211106_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.ImageField(null=True, upload_to='animals/'),
        ),
    ]
