# Generated by Django 3.2.9 on 2021-11-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='health_issues',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
