# Generated by Django 3.2.9 on 2021-11-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_health_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='good_with_children',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='house_trained',
            field=models.CharField(max_length=255),
        ),
    ]
